version: "2.1"

volumes:
  couchpotato:
  plex:
  sickrage:
  jackett:
  rutorrent: 
  plexpy: 
  plexpy-logs: 

services:
  couchpotato:
    container_name: couchpotato
    image: "linuxserver/couchpotato"
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - "5050:5050"
    volumes:
      - couchpotato:/config
      - ${TORRENTS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    restart: always
  
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      TZ: ${TIMEZONE}
    hostname: PlexServer
    volumes:
      - plex:/config
      - ${SHOWS_DIR}:/data/tvshows
      - ${MOVIES_DIR}:/data/movies
  
  sickrage: 
    container_name: sickrage
    image: linuxserver/sickrage
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - 8081:8081
    volumes:
      - sickrage:/config
      - ${TORRENTS_DIR}:/downloads
      - ${SHOWS_DIR}:/tv
    restart: always

  rutorrent:
    container_name: rutorrent
    image: linuxserver/rutorrent
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports:
      - 8112:80
      - 5001:5000
      - 51413:51413
      - 6881:6881/udp
    restart: always
    volumes:
      - ${TORRENTS_DIR}:/downloads
      - rutorrent:/config

  plexpy:
    container_name: plexpy
    image: "linuxserver/plexpy"
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - "8181:8181"
    volumes:
      - plexpy:/config
      - plexpy-logs:/logs:ro
      - ${SHOWS_DIR}:/tv
    restart: always

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - 9117:9117
    volumes:
      - jackett:/config
      - ${TORRENTS_DIR}/auto-load:/downloads
    restart: always