version: "2.1"
services:
  couchpotato:
    container_name: couchpotato
    image: "couchpotato/couchpotato"
    container_name: "couchpotato"
    volumes:
      - "${TORRENTS_DIR}:/datadir"
      - "${MOVIES_DIR}:/media"
    environment:
      CONFIG: /datadir/config/couchpotato/couchpotato.ini
      CP_UID: ${UID}
      CP_GID: ${UID}
    ports:
      - "5050:5050"
    restart: always
  
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ= Europe/Amsterdam
    hostname: PlexServer
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${SHOWS_DIR}:/data/tvshows
      - ${MOVIES_DIR}:/data/movies
  
  sickrage:
    container_name: sickrage
    image: "sickrage"
    ports: 
     - "8081:8081"
    volumes:
      - "${CONFIG_DIR}/sickrage:/config"
      - "${TORRENTS_DIR}:/downloads"
      - "${SHOWS_DIR}:/tv"
    restart: always

  rutorrent:
    container_name: rutorrent
    image: linuxserver/rutorrent
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: Europe/Amsterdam
    ports:
      - 8112:80
      - 5001:5000
      - 51413:51413
      - 6881:6881/udp
    restart: always

  plexpy:
    container_name: plexpy
    image: linuxserver/plexpy
    volumes:
      - "${CONFIG_DIR}/plexpy:/config"
      - "${CONFIG_DIR}/plexpy/logs:/logs:ro"
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: Europe/Amsterdam
    ports:
      - 8181:8181
    restart: always