version: "3"

volumes:
  couchpotato:
  plex:
  sonarr:
  jackett:
  deluge: 
  plexpy: 
  plexpy-logs: 
  headphones:
  plexrequests:

services:
  couchpotato:
    container_name: couchpotato
    image: "linuxserver/couchpotato"
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - "5050:5050"
    volumes:
      - couchpotato:/config
      - ${TORRENTS_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    restart: always
  
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      TZ: ${TIMEZONE}
    hostname: PlexServer
    volumes:
      - plex:/config
      - ${SHOWS_DIR}:/data/tvshows
      - ${MOVIES_DIR}:/data/movies
  
  sonarr: 
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - 8989:8989
    volumes:
      - sonarr:/config
      - ${TORRENTS_DIR}:/downloads
      - ${SHOWS_DIR}:/tv
    restart: always

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports:
      - 8112:80
    volumes:
      - ${TORRENTS_DIR}:/downloads
      - deluge:/config
    restart: always

  headphones:
    container_name: headphones
    image: linuxserver/headphones
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - 8182:8181
    volumes:
      - headphones:/config
      - ${TORRENTS_DIR}:/downloads
      - ${MUSIC_DIR}:/music
    restart: always

  plexpy:
    container_name: plexpy
    image: "linuxserver/plexpy"
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - "8181:8181"
    volumes:
      - plexpy:/config
      - plexpy-logs:/logs:ro
      - ${SHOWS_DIR}:/tv
    restart: always

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    environment:
      PGID: ${UID}
      PUID: ${UID}
      TZ: ${TIMEZONE}
    ports: 
     - 9117:9117
    volumes:
      - jackett:/config
      - ${TORRENTS_DIR}/auto-add:/downloads
    restart: always

  plexrequests:
    container_name: plexrequests
    image: linuxserver/plexrequests
    environment:
      PGID: ${UID}
      PUID: ${UID}
    ports: 
     - 9200:3000
    volumes:
      - plexrequests:/config
    restart: always